# Niveles de log
server:
  port: ${SEVER_PORT:8088}
logging:
  level:
    org.springframework.security: INFO #DEBUG
    org.springframework.security.web.FilterChainProxy: INFO
# Log de datasource-hikari
    #com.zaxxer.hikari: INFO #DEBUG
    #org.springframework.jdbc.datasource: INFO #DEBUG
# Log de aplicacion
    root: INFO  #TRACEINFO
    com.alineumsoft: INFO
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5

# Congiguracion general aplicacion
# En ambiente de pruebas habilitar la propiedad profile.active: test
spring:
  #profiles:
    #active: test
  application:
    name: security-zenwk
  messages:
    basename: i18n/
    fallback-to-system-locale: false
  jpa:
    #hibernate.ddl-auto: "create-drop"
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true
  security:
    user:
      name: user
      password: User침193@
# Congiguracion aplicacion personalizada
app:
# Internacionalizacion
  default:
    locale: es
# Data source
  datasource:
    hikari:
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5432/zenwk}
      username: ${DB_USER:calegria}
      password: ${DB_PASSWORD:calegria}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, loggers
  endpoint:
    health:
      show-details: never
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  metrics:
    enabled: true
# Deshablitar / hablitar autienciaci칩n perfil de pruebas
security:
  test-config:
    config.enabled: test
  # Configuraci칩n seguridad jwt
  jwt:
    # Clave secreta para la generaci칩n de tokens JWT
    secret: ${JWT_SECRET:U3VwM1I1Y1IzdFA0czVXMHJEIFwU3VwM1I1Y1IzdFA0czVXMHJEIFw=}
    # Tiempo en milisegundos que dura la validez del token JWT (24 horas)
    expiration-time: ${JWT_EXPIRATION:86400000}
    # Prefijo del token JWT 
    token-prefix: Bearer
    # Nombre del encabezado HTTP que contiene el token JWT
    header-string: Authorization
    # Activa el uso de tokens JWT para la seguridad 
    enabled: true 

